/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_ile_AdaptionHandler */

#ifndef _Included_com_intel_ile_AdaptionHandler
#define _Included_com_intel_ile_AdaptionHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
