/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_ile_CloudWave */

#ifndef _Included_com_intel_ile_CloudWave
#define _Included_com_intel_ile_CloudWave
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_ile_CloudWave_CW_SOURCE_APPLICATION
#define com_intel_ile_CloudWave_CW_SOURCE_APPLICATION 1L
#undef com_intel_ile_CloudWave_CW_SOURCE_VM
#define com_intel_ile_CloudWave_CW_SOURCE_VM 2L
#undef com_intel_ile_CloudWave_CW_SOURCE_LOGSERVER
#define com_intel_ile_CloudWave_CW_SOURCE_LOGSERVER 3L
#undef com_intel_ile_CloudWave_CW_SOURCE_ESPER
#define com_intel_ile_CloudWave_CW_SOURCE_ESPER 4L
#undef com_intel_ile_CloudWave_CW_METRIC_GAUGE
#define com_intel_ile_CloudWave_CW_METRIC_GAUGE 1L
#undef com_intel_ile_CloudWave_CW_METRIC_DELTA
#define com_intel_ile_CloudWave_CW_METRIC_DELTA 2L
#undef com_intel_ile_CloudWave_CW_METRIC_CUMULATIVE
#define com_intel_ile_CloudWave_CW_METRIC_CUMULATIVE 3L
#undef com_intel_ile_CloudWave_CW_METRICEVENTTYPE_GAUGE
#define com_intel_ile_CloudWave_CW_METRICEVENTTYPE_GAUGE 1L
#undef com_intel_ile_CloudWave_CW_METRICEVENTTYPE_DELTA
#define com_intel_ile_CloudWave_CW_METRICEVENTTYPE_DELTA 2L
#undef com_intel_ile_CloudWave_CW_METRICEVENTTYPE_CUMULATIVE
#define com_intel_ile_CloudWave_CW_METRICEVENTTYPE_CUMULATIVE 3L
#undef com_intel_ile_CloudWave_CW_TARGET_MERLIN
#define com_intel_ile_CloudWave_CW_TARGET_MERLIN 1L
#undef com_intel_ile_CloudWave_CW_TARGET_MESSINA
#define com_intel_ile_CloudWave_CW_TARGET_MESSINA 2L
#undef com_intel_ile_CloudWave_CW_TARGET_CEILOMETER
#define com_intel_ile_CloudWave_CW_TARGET_CEILOMETER 3L
#undef com_intel_ile_CloudWave_CW_SEVERITY_LOW
#define com_intel_ile_CloudWave_CW_SEVERITY_LOW 1L
#undef com_intel_ile_CloudWave_CW_SEVERITY_MEDIUM
#define com_intel_ile_CloudWave_CW_SEVERITY_MEDIUM 2L
#undef com_intel_ile_CloudWave_CW_SEVERITY_HIGH
#define com_intel_ile_CloudWave_CW_SEVERITY_HIGH 3L
#undef com_intel_ile_CloudWave_CW_DATA_TYPE_INTEGER
#define com_intel_ile_CloudWave_CW_DATA_TYPE_INTEGER 1L
#undef com_intel_ile_CloudWave_CW_DATA_TYPE_LONG
#define com_intel_ile_CloudWave_CW_DATA_TYPE_LONG 2L
#undef com_intel_ile_CloudWave_CW_DATA_TYPE_LONGLONG
#define com_intel_ile_CloudWave_CW_DATA_TYPE_LONGLONG 3L
#undef com_intel_ile_CloudWave_CW_DATA_TYPE_REAL
#define com_intel_ile_CloudWave_CW_DATA_TYPE_REAL 4L
#undef com_intel_ile_CloudWave_CW_DATA_TYPE_DOUBLE
#define com_intel_ile_CloudWave_CW_DATA_TYPE_DOUBLE 5L
#undef com_intel_ile_CloudWave_CW_DATA_TYPE_STRING
#define com_intel_ile_CloudWave_CW_DATA_TYPE_STRING 6L
#undef com_intel_ile_CloudWave_CW_EMERGENCY
#define com_intel_ile_CloudWave_CW_EMERGENCY 0L
#undef com_intel_ile_CloudWave_CW_ALERT
#define com_intel_ile_CloudWave_CW_ALERT 1L
#undef com_intel_ile_CloudWave_CW_CRITICAL
#define com_intel_ile_CloudWave_CW_CRITICAL 2L
#undef com_intel_ile_CloudWave_CW_ERROR
#define com_intel_ile_CloudWave_CW_ERROR 3L
#undef com_intel_ile_CloudWave_CW_WARNING
#define com_intel_ile_CloudWave_CW_WARNING 4L
#undef com_intel_ile_CloudWave_CW_NOTICE
#define com_intel_ile_CloudWave_CW_NOTICE 5L
#undef com_intel_ile_CloudWave_CW_INFO
#define com_intel_ile_CloudWave_CW_INFO 6L
#undef com_intel_ile_CloudWave_CW_DEBUG
#define com_intel_ile_CloudWave_CW_DEBUG 7L
/*
 * Class:     com_intel_ile_CloudWave
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_ile_CloudWave_version
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    current_timestamp
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_ile_CloudWave_current_1timestamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_metric
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1metric__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IJ
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jlong);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_metric
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1metric__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ID
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jdouble);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_metric
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1metric__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_event
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1event__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IJ
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jlong);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_event
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1event__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ID
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jdouble);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_event
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1event__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_proxy_metric
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1proxy_1metric__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IJJLjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jlong, jlong, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_proxy_metric
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IDJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1proxy_1metric__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IDJLjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jdouble, jlong, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_proxy_metric
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1proxy_1metric__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2JLjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jstring, jlong, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_proxy_event
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1proxy_1event__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IJJLjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jlong, jlong, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_proxy_event
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IDJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1proxy_1event__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IDJLjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jdouble, jlong, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_proxy_event
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1proxy_1event__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2JLjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint, jstring, jlong, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    set_logId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_ile_CloudWave_set_1logId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    get_logId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_ile_CloudWave_get_1logId
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    record_native
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_record_1native
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    PostEnactment_long
 * Signature: (Lcom/intel/ile/CloudWave/EnactmentPoint;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_PostEnactment_1long
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    PostEnactment_double
 * Signature: (Lcom/intel/ile/CloudWave/EnactmentPoint;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_PostEnactment_1double
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    PostEnactment_string
 * Signature: (Lcom/intel/ile/CloudWave/EnactmentPoint;)V
 */
JNIEXPORT void JNICALL Java_com_intel_ile_CloudWave_PostEnactment_1string
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    SubscribeToAdaption
 * Signature: (Ljava/lang/String;Lcom/intel/ile/AdaptionHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_ile_CloudWave_SubscribeToAdaption
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_intel_ile_CloudWave
 * Method:    UnSubscribeToAdaption
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_ile_CloudWave_UnSubscribeToAdaption
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
